### ISSUE TITLE
Ports for Rails 5.2.2 / Redmine 4.0.x

### ISSUE THREAD

**Issue by deining** [tleish/redmine_jstoolbar_ext_images#10]
Unfortunately, the plugin does not work with newer Ruby versions:
Startup fails do to unsupported command
ActionDispatch::Callbacks.to_prepare

This can be fix by modifiying the method call in init r.b to:

```
if Rails::VERSION::MAJOR >= 5 and Rails::VERSION::MINOR >= 1
  ActiveSupport::Reloader.to_prepare do
    require_dependency 'wiki_formatting_macros_patch'
  end
elsif Rails::VERSION::MAJOR >= 3
  ActionDispatch::Callbacks.to_prepare
    require_dependency 'wiki_formatting_macros_patch'
  end
```

Startup succeeds then, however, plugin still does not work with latest Redmine version 4.0.x

Any help is appreciated here.

**Comment by tleish** [comment]
Sorry, I no longer use Redmine and cannot effectively update and maintain this repo.  If interested, I'd be happy to pass ownership over to you.
