### ISSUE TITLE
Wrong project description

### ISSUE THREAD

**Issue by deining** [tleish/redmine_jstoolbar_ext_images#11]
This project ``JsToolbar Images extenion`` has a wrong description:

Click on tab ``Code`` and in the first lines below the tabs there is written:

```
Redmine uses CodeRay for code syntax highlighting.
The Redmine jsToolbar CodeRay Extension adds a
button to the Redmine wiki and text editor toolbar
for quick insert of all supported code syntax highlighting 
```

This is somehow confusing.
Most likely you copied the project from the already existing ``coderay`` plugin and missed to change the description?

**Comment by tleish** [comment]
Likely a copy/paste error.  I no longer use Redmine and cannot effectively update and maintain this repo.  Closing for now
