### ISSUE TITLE
Not work with  Bitnami redmine redmine-3.2.0-0

### ISSUE THREAD

**Issue by walkwolf** [tleish/redmine_jstoolbar_ext_images#3]
1.start $install_home/use_redmine 
2. cd plugin dir ,and git clone https://github.com/tleish/redmine_jstoolbar_ext_images
3.
bash-4.1$ rake redmine:plugins RAILS_ENV=production
rake aborted!
Redmine::PluginNotFound: Redmine::PluginNotFound
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:123:in `find'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:251:in`requires_redmine_plugin'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_jstoolbar_ext_images/init.rb:11:in `block in <top (required)>'
......

**Comment by tleish** [comment]
The installation is missing the required redmine_jstoolbar_ext plugin.  

From the README:

> # Requirements
> 
> This plugin requires the [Redmine jsToolbar Ext plugin](https://github.com/tleish/redmine_jstoolbar_ext) > to also be installed.

For clarity, I updated the installation steps in the README to:

## Installation

```
$ cd redmine/plugins
$ git clone https://github.com/tleish/redmine_jstoolbar_ext
$ git clone https://github.com/tleish/redmine_jstoolbar_ext_images
```
